### ISSUE TITLE
Kasatha ancestry attribute boosts are incorrect

### ISSUE THREAD

**Issue by pinkflumph** [TikaelSol/starfinder-field-test#16]
Two Ancestries have incorrect Attribute Boosts/Flaws:
- The Barathu have a boost in Dex instead of boosts in Con, Wis and a free boost, and a flaw in Dex
- The Kasatha are missing a boost in Str and a flaw in Cha

**Comment by TikaelSol** [comment]
Already fixed, duplicate of #9

**Comment by TikaelSol** [comment]
Oh, going too fast on my phone. I'll fix kasatha later
