### ISSUE TITLE
Soldier Walking Armory 

### ISSUE THREAD

**Issue by Locotomo** [TikaelSol/starfinder-field-test#17]
At the moment , bulk cannot be adjusted by the constitution modifier.

**Comment by iron2k2** [comment]
To add to this, it also doesn't count your CON mod for meeting the STR requirement of armor.

**Comment by TikaelSol** [comment]
Partiallty addressed by 6.0.3

There's currently no way to handle swapping the con for str for meeting armor str requirements.
