### ISSUE TITLE
SF2e Dark mode character sheet issues

### ISSUE THREAD

**Issue by HurtboxTV** [TikaelSol/starfinder-field-test#187]
Having an issue with the dark mode player sheet's, the spell and feat names are dark and near unreadable. Light mode sheets are the only way my players can use this sheet atm, even though we like the dark mode especially one of my players with bad eyesight.
<img width="534" alt="huilhhli" src="https://github.com/user-attachments/assets/fb3388ac-0d91-473e-af15-e1ab1fd2b2a4" />
<img width="535" alt="uhiohiuh" src="https://github.com/user-attachments/assets/fb10fd14-addd-4565-bf76-0cd29f7b9017" />

**Comment by TikaelSol** [comment]
Try with no other modules, particularly UI modules.

![image](https://github.com/user-attachments/assets/be318bf5-d752-4601-8799-c0d2870042b5)
