### ISSUE TITLE
Solar Weapon Twin Weapon features not working correctly

### ISSUE THREAD

**Issue by Everrick158** [TikaelSol/starfinder-field-test#36]
2 problems found. 

1. If you do not choose agile as the first trait, it does not appear as an option in the second field. 
2. There is currently no way to create a secondary weapon when using the twin weapon feat. I worked around this myself by copying the effect and replacing all references for "solar-weapon" with a new "solar-weapon-twin" and just having two effects on the character. 

Thanks for all the work you've done!

**Comment by TikaelSol** [comment]
The twin stations feat has an effect for the twin weapon

**Comment by InfamousSky** [comment]
can't repo the agile issue, thou I linked the twin solar weapon effect on the twin solar weapon feat

**Comment by Everrick158** [comment]
I must have something conflicted with the selection boxes then. 

Thank you for all the work you do!
