### ISSUE TITLE
Envoy style "From the Shadows" gives wrong skill feat

### ISSUE THREAD

**Issue by r0sshk** [TikaelSol/starfinder-field-test#37]
The "From The Shadows" Envoy leadership style ought to give Assurance (Stealth), but in the current version of the module it instead gives Assurance (Crafting).

**Comment by Suldrun45** [comment]
From what I can see, it does give Assurance (Stealth) but only if Stealth is already trained before selecting From the Shadows. FtS gives both Stealth and Assurance but it seems the Assurance feat cannot detect the added Stealth skill.

**Comment by InfamousSky** [comment]
looks like it's not giving stealth as an option correctly as it's being added as a proficiency at the same time as the grantItem fires?

**Comment by TikaelSol** [comment]
The underlying system issue has been fixed
