### ISSUE TITLE
Multiple Data Entry Errors - Fabricator Skill Feat and Spacefarer Background and Double Tap Feat

### ISSUE THREAD

**Issue by Karumac** [TikaelSol/starfinder-field-test#55]
Fabricator is a Skill Feat incorrectly categorized as General Feat in Compendium.

Spacefarer Background:
Incorrectly granting the Survival Skill instead of the Piloting Skill.
Incorrectly granting the Forager Skill Feat instead of the Express Driver Skill Feat.
Description should mention the Drift Lore skill, not specific creature type.

Double Tap Operative Feat incorrectly set as a Passive instead of Two-Action activity.

**Comment by SoilentBrad** [comment]
@TikaelSol module version 6.1.1: only the Double Tap feat and Spacefarer background were fixed. Fabricator is still set as just a General feat rather than Skill feat.
