### ISSUE TITLE
Typo in Flashlight Roll Option (found fix)

### ISSUE THREAD

**Issue by Trashloot** [TikaelSol/starfinder-field-test#57]
It should say: 
`{"domain":"all","key":"RollOption","option":"flashlight-lit","toggleable":true,"label":"SF2E.SpecificRule.Equipment.Flashlight-Lit"}`
But the one within the module says: 
`{"domain":"all","key":"RollOption","option":"flashlight-lit","toggleable":true,"label":"SF2E.SpecificRule.Equipment.Flashlight.Lit"}`

If you replace the last . with an - the flashlight works.

**Comment by TikaelSol** [comment]
Works for me. The label wouldn't prevent it from working regardless, and the localization path was working as is.
