### ISSUE TITLE
Envoy Get 'Em - Lead By Example

### ISSUE THREAD

**Issue by nlblunt** [TikaelSol/starfinder-field-test#66]
Lead by example using the Get 'Em feature adds an incorrect damage modifier for the Envoy. The additional damage should be 1 + 1/2 Charisma Modifier. It is currently calculating 1 + Charisma Modifier.

**Comment by TikaelSol** [comment]
This was fixed in a previous release, make sure you are up to date and set the actor to level 0 then back up to reset their class features with new copies
