### ISSUE TITLE
Iconics missing a few feats

### ISSUE THREAD

**Issue by Suldrun45** [TikaelSol/starfinder-field-test#7]
There are a few feats missing on the Iconics:
Chk-Chk (level 1) doesn't have the BG skill feat (Holy Talisman)
Dae (level 5) doesn't have the level 4 class feat (Reactive Strike)
Navasi (level 5) doesn't have the level 1 class feat (Acquire Asset)

**Comment by TikaelSol** [comment]
Chk-Chk had the feat, but as a bonus feat. It's been moved to the BG slot now. Navasi has been fixed.

Dae has reactive strike. The 2nd level feat (shattering strike) doesn't exist, and that has already been reported to Paizo.
