### ISSUE TITLE
"Effect: Get Em" Discrepancies

### ISSUE THREAD

**Issue by Evilson006** [TikaelSol/starfinder-field-test#74]
Issues
- The "Effect: Get'Em" applies to the token that is selected and not targeted. 
- The duration of the effect lasts until the start of the effected tokens turn instead of the start of the Envoy's turn.

I am new to Foundry as well as GitHub although I did test this effect in a few different ways to see if it was user error. However, if I have made a user error please inform me so. Thank you.

**Comment by TikaelSol** [comment]
Not sure what you mean by this. The GM needs to drag the effect onto the target, since players don't have any access. As for the duration, as long as it is applied during the Envoy's turn it should expire at the start of their next turn.
