### ISSUE TITLE
Solarian Photon-attuned Solar Shot is not appearing as an Attack

### ISSUE THREAD

**Issue by Beorod** [TikaelSol/starfinder-field-test#76]
When Attuned to Photon as a Solarian, Solar Shot is not appearing as an attack. It works properly when Graviton attuned.

**Comment by TikaelSol** [comment]
We can fix this as a data issue by being specific with the slugs for each solar shot and changing selectors on Solar Barrage and Unstable Flare to use both new slugs, but this is ultimately some unwanted system behavior where it's colliding the slugs when one fails predication.

**Comment by TikaelSol** [comment]
The system has fixed the underlying bug
