### ISSUE TITLE
Discrepancy in Envoy Proficiencies

### ISSUE THREAD

**Issue by JulietTheCooliet** [TikaelSol/starfinder-field-test#8]
Sorry if this isn't the right place for this, but the playtest envoy gains expert weapon proficiency at level 5 according to the playtest, and upon making a Envoy in foundry using the latest version, at level 5 they only have trained. This is only an issue in the expert level band, master works as per the playtest rules.

**Comment by bloodearnest** [comment]
This still seems to be an issue with 6.0.4?

![image](https://github.com/user-attachments/assets/17fc6c49-091b-484a-b678-4abbd72b6a0b)
