### ISSUE TITLE
Veskarium Imperial Plate price is 10x wrong

### ISSUE THREAD

**Issue by dharkus5000** [TikaelSol/starfinder-field-test#89]
in the pdf Veskarium Imperial Plate is listed as 325 credits, but in foundry it's 325gp, which is wrong, as 1cred=1sp, not gp

**Comment by ammalagonc** [comment]
Hey there, 

I just checked on my end and noticed that the Veskarium Imperial Plate is listed as 325 sp

![image](https://github.com/user-attachments/assets/d2204282-c5e4-42dc-832a-1e0880a4c105)

Try refreshing and re-importing just in case.

**Comment by dharkus5000** [comment]
yeh, GM didn't have the most recent version
