### ISSUE TITLE
Barathu list a 25 foot land speed but have a feat that increases their land speed to 20 feet.

### ISSUE THREAD

**Issue by dallinstone** [TikaelSol/starfinder-field-test#9]
1) They do not have correct default ability scores (should be con/wis/free with dex flaw, instead it just has +dex and blank on the other two) 
2) Barathu have default 5 feet of movement speed (in addition to the fly speed). The module is showing 25 feet. 
3) Barathu languages should be common + brethedan by default, but instead only have common. 

I'll also submit a PR if they're open but figured I'd document here first.

**Comment by dallinstone** [comment]
never mind -- can't figure out what you've got goin' on with file types. If you can provide some guidance on how to manipulate the data I'd be happy to help fix PR's though!

**Comment by dallinstone** [comment]
4. Adaptable Limbs ancestry feet is not providing 20 feet of land speed

**Comment by TikaelSol** [comment]
They have a 25 foot speed in the PDF.
![image](https://github.com/user-attachments/assets/b8c82236-11fb-4921-801b-ba15052c7869)

The other things are fixed, the module is not currently accepting PRs. That will change when I set up an extract process

**Comment by dallinstone** [comment]
![image](https://github.com/user-attachments/assets/6113b4b6-3525-42a7-97bf-d8532c41855d)

Not sure if reddit posts from Paizo folks count as official, but it was corrected here: https://www.reddit.com/r/Starfinder2e/comments/1ehhh0q/starfinder_playtest_errata/

(Not nitpicking, just informing, because otherwise the "Adaptable Limbs" feat makes you lose land speed)
